name: Dev.to - pull articles

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  pull_articles:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - run: npm install
      - run: npx devto run dev init -p
        env:
          DEVTO_TOKEN: ${{ secrets.DEVTO_TOKEN }}
          DEVTO_REPO: dev-to-contents/articles
      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Pull articles
          delete-branch: true
          title: Pull articles
          branch: create-pull-request/patch-pull-articles-devto
