name: Dev.to - publish articles

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish_articles:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - run: npm install
      - run: npx devto run dev push
        env:
          DEVTO_TOKEN: ${{ secrets.DEVTO_TOKEN }}
          DEVTO_REPO: dev-to-contents/articles
      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Publish articles
          delete-branch: true
          title: Publish articles
          branch: create-pull-request/patch-publish-articles-devto
